
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: test1234
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: iro_wor_development

test:
  <<: *default
  database: iro_wor_test

production:
  <<: *default
  database: iro_wor_production
  username: iro_wor2
  password: <%= ENV['MICROS_IRO_WOR_DATABASE_PASSWORD'] %>
